version: "3"

services:
  spring-boot-mongo:
    image: mongo:latest
    container_name: spring-boot-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourUsername
      MONGO_INITDB_ROOT_PASSWORD: yourPassword
      MONGO_INITDB_DATABASE: Keploy
