services:
  java-dedup:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION:-8}
    container_name: dedup-java
    ports:
      - "8080:8080"
    environment:
      KEPLOY_JAVA_CLASS_DIRS: /app/target/classes
