FROM gcr.io/distroless/java17-debian12:nonroot

WORKDIR /app

COPY --chown=10001:10001 target/java-dedup-0.0.1-SNAPSHOT.jar /app/app.jar
COPY --chown=10001:10001 target/jacocoagent.jar /app/jacocoagent.jar

EXPOSE 8080
USER 10001:10001
ENTRYPOINT ["java", "-javaagent:/app/jacocoagent.jar=destfile=/tmp/jacoco.exec", "-jar", "/app/app.jar"]
