name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'petclinic-junit'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        maven-version: '3.8.4'

    - name: Download and prepare Keploy binary
      run: |
        curl --silent --location 'https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz' | tar xz -C /tmp
        sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploybin

    - name: Build and test with Maven and Keploy
      run: |
        cd spring-petclinic/spring-petclinic-rest
        mvn clean install -Dmaven.test.skip=true
        mvn test

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          spring-petclinic/spring-petclinic-rest/target/site/e2e-ut-aggregate/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: Code Coverage
        update-comment: true
        pass-emoji: ':green_circle:'
        ail-emoji: ':red_circle:'

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

    - name: Fail PR if coverage of changed files is less than 60%
      if: ${{ steps.jacoco.outputs.coverage-changed-files < 01.0 }}
      run: |
        echo "Coverage of changed files is less than 60%!"
        exit 1

    
